#+TITLE: Thermos UI

The THERMOS web interface.

Builds using scripts in build-src.

* System dependencies

The application uses two external components

- A postgres / postgis database
- The model solver

Nix expressions for creating a postgis server are in ~dev/pg-server.nix~.
The solver is checked out as a submodule in ~deployment/model~.
Nix expressions for a deployment system are in ~deployment~.

* Configuration

The application has a few config settings, defaults in ~resources/config.edn~.
These are settable through the environment.

* Tooling

We had leiningen, and then we had boot, which were both a pain as things got more complicated.
Now there's some simple clojure programs in ~build-src~ which do the compilation or development.

They are a bit longer than equivalent ~build.boot~ but also easier to make work.

To run for development you can invoke

clojure -Adev:server:client dev

and to build a combined jar you can invoke

clojure -Adev:server:client jar

* Notes

We cannot upgrade the clojurescript compiler without reviewing other JS dependencies.
Any later version of cljs (actually of google closure) has removed the feature for processing AMD modules into CommonJS modules, which we need.


