#+TITLE: THERMOS Terms and Conditions of Use
#+AUTHOR: CSE

This document sets out the terms and conditions on which you may use the
full version of THERMOS at [[https://tool.thermos-project.eu/]]
(*THERMOS*), and the ways in which we (the THERMOS project consortium)
may use data entered into a THERMOS installation.

To let you preview THERMOS without having to install it yourself, we are
providing a restricted version for free public access running on the
server available at [[https://tool.thermos-project.eu/][https://tool.thermos-project.eu]].

Use of the Public Access Version is subject to the terms available here:
[[https://tool.thermos-project.eu/help/data-protection.html]].

You may also run your own copy of THERMOS, in which case you will be in
charge of your data. The source code is available under an open-source
license from [[https://github.com/cse-bristol/110-thermos-ui][https://github.com/cse-bristol/110-thermos-ui]].
If you would like help with this, contact the Centre for Sustainable
Energy ([[https://www.cse.org.uk/][https://www.cse.org.uk]] / [[mailto:thermos@cse.org.uk][thermos@cse.org.uk]]).

I you would like unrestricted access to a thermos installation without
having to set it up yourself, please see [[https://www.cse.org.uk/thermos-subscription]]
for how to request a paid subscription.

1. *This service*

   By using THERMOS, you acknowledge and accept these terms and
   conditions on behalf of yourself and all individual users from your
   organisation:

   1.  All use of THERMOS is subject to these terms and conditions and
       to you obtaining the appropriate Subscription. The number of
       individual users who are permitted to use THERMOS depends on the
       type of Subscription you obtain. Further information including
       fee structures is available at: xxxxx

   2.  We have the right to immediately terminate this agreement and
       remove your access to THERMOS in the event that you (or any of
       your individual users) breach these terms. You will not be
       entitled to any refund.

   3.  Login details must not be shared with anybody else, either inside
       or outside your organisation.

   4.  We will take reasonable steps to ensure that THERMOS is available
       to you. However, we are not providing any warranty, guarantee, or
       representation of any kind. THERMOS is provided as is, and as
       available. We do not warrant that THERMOS is error free or that
       you will be able to operate it without problems or interruptions.

   5.  We may update any of the algorithms that comprise THERMOS at any
       time, and do not guarantee consistency with previous versions.

   6.  You assume sole responsibility for results and conclusions
       obtained from your use of THERMOS. We take no responsibility for,
       and make no guarantee of the accuracy of, any of the outputs from
       THERMOS: you are responsible for ensuring that the outputs are
       fit for whatever purpose you may have. We shall have no liability
       for any losses resulting from any use of THERMOS. Our total
       liability to you shall be limited to the amount of £1 plus the
       cost of the last Subscription you purchased.

   7.  Where possible we will endeavour to back up all user data on a
       daily basis, and store it securely off-site.

   8.  In the event of a technical fault, we will endeavour to restore
       the service within 7 days using the most recent available data
       backup, but we do not guarantee how recent this backup will be,
       and you are advised to download and backup any critical data on a
       regular basis.

   9.  Any bugs identified should be reported using the online form at
       tool.thermos-project.eu/bug-report. We will consider all bug
       reports, but we will not be obliged to take any action in
       response.

   10. You may provide suggestions, comments or other feedback regarding
       THERMOS, but we will not be obliged to take any action in
       response.

   11. Publication of any results which have involved the use of THERMOS
       is done entirely at the user's risk. Any work produced as a
       result of your use of THERMOS, (including, for example an
       academic publication or commercial report) which incorporates or
       references outputs from THERMOS, must contain the following
       acknowledgement:

#+begin_quote
  /This work uses results from the THERMOS (Thermal Energy Resource
  Modelling and Optimisation System) model. THERMOS was an EU Horizon
  2020 funded research project (grant agreement No 723636) coordinated
  by the Centre for Sustainable Energy./

  /THERMOS provides heat network data and modelling tools in a
  user-friendly open-source application which makes network planning
  faster, easier, and more cost effective./

  /For more information about THERMOS see the THERMOS website
  at [[https://www.thermos-project.eu/][https://www.thermos-project.eu/]]
  or contact the Centre for Sustainable Energy: [[https://www.cse.org.uk/][https://www.cse.org.uk]] /
  [[mailto:thermos@cse.org.uk][thermos@cse.org.uk]]
#+end_quote

12. Unless you have made separate arrangements, no user-support is
    available.

1. *User Data*

   1. THERMOS does not process very much personal data. To the extent
      that it does, we will at all times comply with data protection
      laws. We are not interested in spying on you or building business
      leads.

   2. The information you can enter about yourself is limited to (1)
      your name and (2) your email address (and those of your other
      individual users, if any). You must not provide us with any
      personal data which you don't have authority to share with us.

   3. We may send emails to you and your registered users for the
      purpose of:

      1. Telling you about changes to the service

      2. Contacting you to ask you about your use of the service, for
         the purposes of assessing the impact and value of the project.

   4. A session cookie will be stored on your computer when you login.
      Session cookies are a mechanism needed for the application to
      remember that you are logged in.

   5. We also record about each user account:

1) When you log in and out of the system,

2) How many projects, maps, and network models you have run,

3) Summary statistics about these data, specifically:

   1. How many participants are collaborating on projects,

   2. How large the maps and networks you create are, and

   3. The geographic location (bounding box) of your maps and networks.

#+begin_quote
  We will not otherwise process or look at your uploaded GIS files,
  except insofar as needed to provide the services you request.
#+end_quote

4) Diagnostic information about errors or faults in the system, and

5) Which other accounts you have worked with; this information is only
   used for access control. We are not interested in building a picture
   of your social network.

   1. To the extent that we act as a processor of personal data on your
      behalf, we shall:

      1. process personal data only in accordance with these terms and
         conditions, or on your documented instructions;

      2. implement appropriate measuresto protect against unauthorised
         or unlawful personal data processing and against accidental
         loss or destruction of or damage to your personal data;

      3. ensure that anyone authorised by us to process your personal
         data have committed themselves to confidentiality or are under
         an appropriate statutory or common law obligation of such;

      4. provide reasonable assistance in responding to any request from
         a data subject and ensuring your compliance with your
         obligations under data protection laws;

      5. notify you without undue delay on becoming aware of a personal
         data breach;

      6. at your choice, delete or return personal data to you after the
         end of the provision of services relating to processing and
         delete existing copies unless otherwise required by applicable
         law;

      7. maintain records to demonstrate our compliance with our data
         protection obligations under these Terms and make these
         available to you on reasonable request, and allow for and
         contribute to audits to assess our compliance.

   2. You acknowledge that we may appoint processors to process your
      personal data, provided that we notify you of any changes and give
      you the opportunity to object to such changes, ensure that such
      processors are subject to substantially equivalent data protection
      obligations to those set out in these Terms and shall remain
      responsible for the acts and omissions of such processors.

2. *Data Security*

   1. All data in THERMOS is stored in a physical server on site at CSE.
      We keep this server updated and secured to reasonable commercial
      standards. Server access is restricted to those indviduals who
      need access in order to manage the system.

   2. If you extend project access to someone else, they will be able to
      see all the data in that project.

   3. All communications to the server are encrypted, so an attacker
      with access to the network infrastructure between your computer
      and the server would not be able to view the data transmitted.

   4. Your data is not encrypted at rest on the server, so an attacker
      who gained privileged access to the machine could view all data
      anyone has uploaded.

3. *Acquiring your data*

   1. At the moment you can download your network diagrams and maps via
      the user interface. If you want to get hold of any other data,
      pleasecontact us and we can work something out. We have no
      interest in holding onto your data so we can wring money out of
      you, and indeed, other than as identified above, are not
      interested in the data itself.

4. *Removing Your Data*

   1. At the moment there is no button to delete your user account, but
      we can delete it for you if you drop us a line. We are looking to
      put in a button to do this, the only reason we haven't yet is that
      we're busy people. You can delete projects, maps, and networks
      through your user account. When you do this, they are genuinely
      deleted in an irrecoverable way.

5. *General*

   1. You cannot assign, transfer, charge, sub-contract any of your
      rights or obligations under these Terms without us agreeing with
      you first.

   2. We may assign, transfer, charge, sub-contract or deal in any other
      manner with all or any of our rights or obligations under these
      Terms.

   3. These Terms and any dispute or claim arising out of or in
      connection with them or their subject matter or formation
      (including non-contractual disputes or claims) shall be governed
      by and construed in accordance with the law of England and Wales
      and you agree that the courts of England and Wales shall have
      exclusive jurisdiction.
