#+TITLE: Creating maps in THERMOS
#+AUTHOR: CSE

In THERMOS, a map contains buildings and paths.
Buildings are places where heat might be used or generated, and paths are places where heat distribution pipes might be placed.

You need to create a map before you can design a heat network. 
Each heat network design will use some of the buildings and paths from a map to assemble a network.
The parameters the network model uses for each path or building will be taken from the map, although you can override the map values if you want when designing the network.

* Creating a project

THERMOS maps and network models are part of /projects/. Projects control who can collaborate on work in the THERMOS application - each project can have several people working on it, and a person can be working on several projects.

There are two ways to get involved in a project:

1. Start a new project yourself
2. Ask someone who has an existing project to invite you to participate on it

* Creating a map from openstreetmap

The easiest way to make a map is by using OpenStreetMap data.

* Creating a map from your own GIS files

If OpenStreetMap does not contain the buildings or roads you want to model, and/or you have better data about the buildings you are interested in, you can produce a map from these files instead of OpenStreetMap.

* How heat demand is estimated

* How buildings are connected up

* Supplying your own demand estimates

* Using benchmark estimates for some buildings

* Setting parameters for paths 
