#+TITLE: THERMOS parameter index
#+AUTHOR: CSE

This document contains a list of the important parameters you can tell THERMOS, what they mean, and where you might get them. 

* Facts about buildings

These parameters are mostly used when creating a map (see [[file:maps.org][here]] for more about creating maps).
Some of them can be edited directly in the [[file:networks.org][network editor]] as well.

** Annual demand

The annual demand for heat in a building, in kWh.

Every building in a map has a value associated with it for annual demand
The value is placed on the building when the map is created, either using a known user input, a benchmark estimate, or the THERMOS heat demand model.

You can edit this demand directly in a network problem by right clicking on a building and selecting ~Edit buildings~. The edit will not change the map, only that problem.

This value affects:

- the revenue for providing heat to the building
- the avoided emissions by providing heat to the building
- the cost of supplying heat into the network

** Peak demand

The peak demand for heat in a building, in kW.

Every building in a map has a value associated with it for peak demand.
The value is placed on the building when the map is created, either using a known user input, a user input peak-to-base ratio, or the THERMOS heat demand model.

You can edit the peak directly in a network problem by right clicking on a building and selecting ~Edit buildings~. The edit will not change the map, only that problem.

This value affects:

- the size (and hence cost) of pipes needed to supply the building
- the size (and hence cost) of the plant needed to supply the network
- the connection costs for the building

** Building height

The average height of a building, in m.

This value is only used during [[file:maps.org::#demand-estimation][heat demand estimation]] with the THERMOS heat demand model. If it is given, it will allow a better regression model to be selected. If building height is not supplied, it may still be extracted from LIDAR data on the server.

** Floor area

The internal floor area of a building, in m^2.

This value is only used during [[file:maps.org::#demand-estimation][heat demand estimation]] with a benchmark. If a value is not given, it is estimated using the building height and a standard storey height. If the building height is not given, a single storey is assumed.

** Benchmark terms

There are two benchmark terms used during [[file:maps.org::#demand-estimation][heat demand estimation]], a constant value and a per m^2 value.

If either value is given, the heat demand is calculated as a linear function of floor area:

$$
\text{constant} + \text{floor area} \times \text{variable}
$$

** Peak to base ratio

A dimensionless value used during [[file:maps.org::#demand-estimation][heat demand estimation]], which relates the annual power consumption to the peak. If this value is supplied, the peak demand is set using the annual demand multiplied by this factor.

For example, if the annual demand were 30 MWh / yr, with a peak to base ratio of 10 the peak demand would be about 34 kW.

** Heat price

The price at which heat is sold to buildings, which determines the revenue from including a building in a network by multiplication with the [[Annual demand][annual demand]].

This is set in the [[file:networks.org][network editor]] in two places: there is a value on each building, which can be edited by right clicking the building, and a default value in the options page which is used for any building that hasn't been so edited.

** Connection cost

The capital cost of work within a building required to connect it to the network. This is separate from the costs of pipework.

The value is denominated in currency / kWp, so if you increase the [[Peak demand][peak demand]] for a building the connection cost will also increase. 

This value is stored on each building, with an initial value provided in the map import page.
It can also be edited for each building in the [[file:networks.org][network editor]], by right clicking on the building.

** TODO Emissions factors

* Facts about pipes

These parameters are used to determine the cost and heat losses for pipes, using [[file:calculations.org][the heat network calculation method]].

** Mechanical engineering costs

The mechanical engineering costs are a simplification reflecting the costs for pipework that are independent of the place where the pipe is being installed, including:

- The cost of buying the pipe from a manufacturer
- The cost of welding the pipe together on site

You can specify these costs for each pipe diameter in the pipe costs table.

For a hot water system the cost entered should be per meter of /both flow and return pipe/ - these are assumed always to be laid together.

For a saturated steam system, the cost entered should be per meter of flow pipe. No return pipe is assumed, as the energy is delivered by condensation at the consumer.

** Civil engineering costs
:PROPERTIES:
:CUSTOM_ID: civil-costs
:END:

The civil engineering costs are a simplification reflecting the costs for pipework that depend on the place where the pipe is being installed, including:

- The cost of digging up the road surface
- The cost of suspending traffic
- The cost of suspending parking

Like the mechanical engineering costs, the civil costs are user inputs entered into the pipe costs table.

** Flow, return, and ground temperatures

These parameters are all controllable in the options page of the network editor.

The flow and return temperature determine the amount of heat that can be transmitted by a pipe of a given diameter, using the equations described [[file:calculations.org][here]]. 
The ground temperature together with the average of the flow and return temperatures determines the heat losses associated with a pipe.

* Heat supply

Heat supply parameters are all controlled by right clicking on a building:

#+ATTR_HTML: :autoplay true :loop true :controls :true
#+CAPTION: Editing heat supply parameters
[[./img/parameters/edit-supply-params.webm]]

** Maximum capacity

Supply maximum capacity limits the size of supply the model will ever construct in a location. Any network connected to this supply cannot require more than this power output at peak time.

** Fixed cost

Supply fixed cost sets the capital cost that will be incurred if /any/ supply is used from a location, no matter the amount.

This could reflect things like:

- The cost of purchasing land
- The administrative and engineering cost of setting up the plant

** Capacity cost

The supply capacity cost sets the capital cost that will be incurred /per unit capacity/ in a location. If the peak demand the supply has to meet is $X$ kW, it costs $X \times \text{capacity cost}$.

This reflects any capital cost that grows as the plant gets bigger.

** Annual cost

The annual cost of a supply is a variable cost incurred each year , /per unit capacity/. 

This reflects costs that come from maintaining the plant which grow as as the plant gets bigger. The annual cost is not tied to the amount of heat sold, just to the size of the peak demand.

** Supply cost

The supply cost is the net cost of producing heat to put into the network. If the network were buying heat from a third party, this is the price they would pay for it. This should include the cost of primary fuel, pumping costs, any administrative costs that grow with the amount of heat sold and so on.

** Emissions factors

Supply emissions factors are the emissions factors associated with producing a unit of heat to put into the network.

* Financial parameters

** Loan term

** Loan interest rate

** NPV term

** NPV discount rate

* Optimisation parameters

** MIP gap

** Time limit
